# Extract Table from Word

In [1]:
from docx import Document
from pathlib import Path
import pandas as pd

In [2]:
def get_df(table):
    num_row = len(table.rows)
    num_col = len(table.rows[0].cells)
    
    header = table.rows[0].cells
    columns = [item.text for item in header]
    
    data = []
    for i in range(1, num_row):
        row = []
        for j in range(num_col):
            text = table.rows[i].cells[j].text
            row.append(text)
        data.append(row)
    
    df = pd.DataFrame(data, columns=columns)
    return df

In [3]:
file_path = Path.cwd() / 'data.docx'
doc = Document(file_path)
table = doc.tables[0]
df = get_df(table)

In [4]:
df

,月份,号,周,节目,讲员/主持人,破冰,领唱,伴唱,吉他,司琴,贝斯,鼓手,电脑,建议歌曲,建议破冰
0,Jul,6,四,启发课程 1: 生命就是如此吗？,谢慧敏传道,键劲,美怡,-,宣扬,-,-,-,谢慧敏传道,1. 欢迎歌\n2. 朋友\n3. 我的未来不是梦,宾果/创意介绍
1,Jul,8,六,青少年讲座《事奉者联盟 The Disciples》,张俊贤教师,-,宣扬,美怡,键劲,佳欣,凯悦,力飞,洛圣,-,-
2,Jul,9,日,青少主日《Be Light·光》,张俊贤教师,-,爱慈,宣扬,键劲,佳欣,凯悦,均荣,依晶,-,-
3,Jul,13,四,启发课程 2: 耶稣是谁？,谢慧敏传道,爱慈,键劲,-,均荣,-,-,-,谢慧敏传道,1. 朋友\n2. 光辉岁月\n3. 耶稣对你真好/是耶稣,猜猜我是谁/真真假假
4,Jul,20,四,启发课程 3: 耶稣为什么死？,谢慧敏传道,美怡,宣扬,-,-,佳欣,-,-,谢慧敏传道,1. 主恩典\n2. 幸福\n3. 有一位神,音乐传球
5,Jul,27,四,启发课程 4: 如何得着信心？,谢慧敏传道,依晶,爱慈,-,宣扬,-,-,-,谢慧敏传道,1. 不动摇的信心\n2. 恩典够用\n3. 我相信,剪刀石头布
6,Aug,4,五,启发课程 5: 为什么祷告？怎样祷告？,谢慧敏传道,诗怡,美怡,-,健劲,-,-,-,谢慧敏传道,1. 满有能力\n2. 我相信\n3. 倾听我的心,数学炸弹
7,Aug,11,五,启发课程 6: 为什么读圣经？怎样读圣经？,谢慧敏传道,力飞,键劲,-,-,佳欣,-,-,谢慧敏传道,1. 朋友\n2. 认定你\n3. 耶稣爱你,Emoji成语
8,Aug,18,五,启发课程 7: 上帝如何指引我们？,谢慧敏传道,洛圣,宣扬,-,凯悦,-,-,-,谢慧敏传道,1. 脚步\n2. 恩典之路\n,请你跟我这样做
9,Aug,25,五,启发课程 8: 如何抵挡邪恶,谢慧敏传道,贤杰,爱慈,-,均荣,-,-,-,谢慧敏传道,1. 大山为我挪开\n2. 耶稣掌权\n3. 有一天,萝卜蹲
10,Aug,31,四,启发课程 9: 圣灵... *启发周末营,待定,待定,宣扬,力添,键劲,佳欣,凯悦,力飞,贤杰,1. 圣灵的江河\n2. 求主充满我\n3. 圣灵请你来/圣灵请你来充满我心,猫抓老鼠
11,Sep,8,五,启发课程 10: 为什么要传福音？怎样传福音？,谢慧敏传道,键劲,美怡,-,-,佳欣,-,-,谢慧敏传道,1. 传爱\n2. 真正好\n3. 人们需要主,剪刀石头布与橡皮筋
12,Sep,15,五,启发课程 11: 上帝今天还医治人吗？,谢慧敏传道,爱慈,键劲,-,宣扬,-,-,-,谢慧敏传道,1. 美好事\n2. 唯有耶稣\n3. 医治的爱,比一比
13,Sep,22,五,启发课程 12: 教会是什么 & 预祝中秋,谢慧敏传道,美怡,宣扬,-,均荣,-,-,-,谢慧敏传道,1. 在主爱中\n2. 看见神的爱\n3. 我们爱让世界不一样,鸡蛋小鸡母鸡
14,Sep,30,六,启发课程13: 如何活得更精彩? *启发之夜,待定,待定,爱慈,宣扬,键劲,佳欣,凯悦,均荣,依晶,1. 恩典已降临\n2. 活出爱\n3. 我需要有你在我生命中,树与松鼠

# Extract Table from PDF

In [5]:
from pathlib import Path
import pandas as pd
import tabula

In [6]:
file_path = Path.cwd() / 'data.pdf'

In [7]:
tables = tabula.read_pdf(file_path, pages='all')
df = pd.concat(tables)

In [8]:
df

,月份,号,周,节目,讲员/主持人,破冰,领唱,伴唱,吉他,司琴,贝斯,鼓手,电脑,Unnamed: 0,建议歌曲,建议破冰,待定
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 欢迎歌,NaN,NaN,NaN
1,NaN,6.0,四,启发课程 1: 生命就是如此吗?,谢慧敏传道,键劲,美怡,-,宣扬,-,-,-,谢慧敏传道,2. 朋友,NaN,宾果/创意介绍,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. 我的未来不是梦,NaN,NaN,NaN
3,NaN,8.0,六,青少年讲座《事奉者联盟 The Disciples》,张俊贤教师,-,宣扬,美怡,键劲,佳欣,凯悦,力飞,洛圣,-,NaN,-,NaN
4,NaN,9.0,日,青少主日《Be Light·光》,张俊贤教师,-,爱慈,宣扬,键劲,佳欣,凯悦,均荣,依晶,-,NaN,-,NaN
5,Jul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 朋友,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,猜猜我是谁/真,NaN
8,NaN,13.0,四,启发课程 2: 耶稣是谁?,谢慧敏传道,爱慈,键劲,-,均荣,-,-,-,谢慧敏传道,2. 光辉岁月,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,真假假,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. 耶稣对你真好/是耶稣,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 主恩典,NaN,NaN,NaN
12,NaN,20.0,四,启发课程 3: 耶稣为什么死?,谢慧敏传道,美怡,宣扬,-,-,佳欣,-,-,谢慧敏传道,2. 幸福,NaN,音乐传球,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. 有一位神,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 不动摇的信心,NaN,NaN,NaN
15,NaN,27.0,四,启发课程 4: 如何得着信心?,谢慧敏传道,依晶,爱慈,-,宣扬,-,-,-,谢慧敏传道,2. 恩典够用,NaN,剪刀石头布,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. 我相信,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 满有能力,NaN,NaN,NaN
18,NaN,4.0,五,启发课程 5: 为什么祷告?怎样祷告?,谢慧敏传道,宣扬,美怡,-,健劲,-,-,-,谢慧敏传道,2. 我相信,NaN,数学炸弹,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. 倾听我的心,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 朋友,NaN,NaN,NaN
21,NaN,11.0,五,启发课程 6: 为什么读圣经?怎样读圣经?,谢慧敏传道,力飞,键劲,-,-,佳欣,-,-,谢慧敏传道,2. 认定你,NaN,Emoji 成语,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. 耶稣爱你,NaN,NaN,NaN
23,Aug,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 脚步,NaN,NaN,NaN
25,NaN,18.0,五,启发课程 7: 上帝如何指引我们?,谢慧敏传道,洛圣,宣扬,-,凯悦,-,-,-,谢慧敏传道,NaN,NaN,请你跟我这样做,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2. 恩典之路,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1. 大山为我挪开,NaN,NaN,NaN
28,NaN,25.0,五,启发课程 8: 如何抵挡邪恶,谢慧敏传道,贤杰,爱慈,-,均荣,-,-,-,谢慧敏传道,2. 耶稣掌权,NaN,萝卜蹲,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3. 有一天,NaN,NaN,NaN
0,月,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,月,号,NaN,节目,讲员/主持,破,NaN,伴,吉,司,贝,鼓手,电脑,NaN,建议歌曲,建议破冰,NaN
1,NaN,31,四,启发课程 9: 圣灵... *启发周末营,待定,待定,宣扬,力添,键劲,佳欣,凯悦,力飞,贤杰,NaN,1. 圣灵的江河\r2. 求主充满我\r3. 圣灵请你来/圣灵请你来充满我心,猫抓老鼠,NaN
2,NaN,NaN,NaN,NaN,待,待,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sep,8,五,启发课程 10: 为什么要传福音?怎样传福音?,谢慧敏传道,键劲,美怡,-,-,佳欣,-,-,谢慧敏传道,NaN,1. 传爱\r2. 真正好\r3. 人们需要主,剪刀石头布与橡\r皮筋,NaN
4,15,五,启发课程 11: 上帝今天还医治人吗?,谢慧敏传道,爱慈,键劲,-,宣扬,-,-,-,谢慧敏传道,1. 美好事\r2. 唯有耶稣\r3. 医治的爱,NaN,比一比,NaN,NaN
5,22,五,启发课程 12: 教会是什么 & 预祝中秋,谢慧敏传道,美怡,宣扬,-,均荣,-,-,-,谢慧敏传道,1. 在主爱中\r2. 看见神的爱\r3. 我们爱让世界不一样,NaN,鸡蛋小鸡母鸡,NaN,NaN
6,30,六,启发课程 13: 如何活得更精彩? *启发之夜,待定,待定,爱慈,宣扬,键劲,佳欣,凯悦,均荣,依晶,1. 恩典已降临\r2. 活出爱\r3. 我需要有你在我生命中,NaN,树与松鼠,NaN,NaN
7,待,待,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,号,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,节目,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,讲员/主持,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,破,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,伴,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,吉,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,司,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,贝,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,鼓手,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,电脑,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,建议歌曲,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,建议破冰,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,待
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,待
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,待
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,待

# Extract Table from Excel

In [9]:
from pathlib import Path
import pandas as pd

In [10]:
file_path = Path.cwd() / 'data.xlsx'
df = pd.read_excel(file_path)

In [11]:
df

,面子书,月份,日,周,备注,节目,分享/主持,破冰,领唱,伴唱,吉他,司琴,贝斯,鼓手,电脑,祷告,食物,建议歌曲,建议破冰,调整
0,键劲,Jan,6,五,NaN,暂停,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
1,NaN,NaN,13,五,NaN,暂停,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
2,NaN,NaN,20,五,22 农历新年,暂停,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
3,NaN,NaN,27,五,NaN,暂停,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
4,爱慈,Feb,3,五,年初十三,迎新会《兔GETHER》,青年团,-,宣扬,爱慈,键劲,佳欣,凯悦,均荣,力飞,-,青年团,NaN,NaN,NaN
5,NaN,NaN,10,五,NaN,小组聚会 1,键劲,-,美怡,-,宣扬,-,-,-,-,爱慈,均荣&爱慈,NaN,NaN,NaN
6,NaN,NaN,17,五,NaN,小组聚会 2,美怡,-,洛圣,-,凯悦,-,-,-,-,键劲,依晶&艺汶,NaN,NaN,NaN
7,NaN,NaN,24,五,NaN,小组聚会 3,宣扬,-,歆妤,-,均荣,-,-,-,-,艺汶,宣扬&洛圣,NaN,NaN,NaN
8,美怡,Mar,3,五,NaN,小组聚会 4,键劲,-,依晶,-,宣扬,-,-,-,-,键劲,力添&力炫,NaN,NaN,分享: 键劲代替均荣，吉他: 宣扬代替键劲，祷告: 键劲代替均荣
9,NaN,NaN,10,五,11 区青少联谊,暂停,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
10,NaN,NaN,17,五,NaN,小组聚会 5,诗怡,-,德喜,-,宣扬,-,-,-,-,依晶,依婷&嘉仪,NaN,NaN,吉他: 宣扬代替凯悦
11,NaN,NaN,24,五,NaN,小组聚会 6,美怡,-,艺汶,-,宣扬,-,-,-,-,依婷,筠霓&爱慈,NaN,NaN,分享: 美怡代替键劲，吉他: 宣扬代替均荣
12,NaN,NaN,31,五,NaN,团契(John),约翰组,-,爱慈,力添,键劲,-,-,-,宣扬,-,青年团,NaN,NaN,NaN
13,诗怡,Apr,7,五,受难日,暂停,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
14,NaN,NaN,14,五,NaN,小组聚会 7,键劲,-,庆良,-,键劲,-,-,-,-,宣扬,健祺&仙平,NaN,NaN,分享: 键劲代替美怡，筠霓: 4月-7月不在拿笃
15,NaN,NaN,21,五,22 Raya,小组聚会 8,宣扬,-,力飞,-,宣扬,-,-,-,-,洛圣,依晶&艺汶,NaN,NaN,领唱: 力飞代替佳欣，吉他: 宣扬代替凯悦，宵夜: 依晶&艺汶代替键劲&庆武
16,NaN,NaN,28,五,29 生命游戏,团契(Joshua),约书亚组,-,佳欣,洛圣,凯悦,-,-,-,歆妤,-,约书亚组,NaN,NaN,NaN
17,依晶,May,5,五,4 卫塞节,小组聚会 9,诗怡,-,诗怡,-,宣扬,-,-,-,-,键劲,键劲&庆武,NaN,NaN,分享: 诗怡代替均荣，祷告: 键劲代替爱慈
18,NaN,NaN,12,五,14 母亲节,小组聚会 10,均荣,-,依晶,-,均荣,-,-,-,-,艺汶,宣扬&洛圣,NaN,NaN,分享: 均荣代替诗怡，领唱: 依晶代替爱慈
19,NaN,NaN,19,五,NaN,小组聚会 11,键劲,-,贤杰,-,凯悦,-,-,-,-,键劲,力添&力炫,NaN,NaN,NaN
20,NaN,NaN,26,五,NaN,团契(John),约翰组,-,洛圣,宣扬,键劲,-,-,-,依晶,-,青年团,NaN,NaN,领唱: 洛圣代替庆良
21,宣扬,Jun,2,五,NaN,小组聚会 12,美怡,-,淑怡,-,宣扬,-,-,-,-,依晶,健祺&仙平,NaN,NaN,NaN
22,NaN,NaN,9,五,NaN,小组聚会 13,宣扬,-,庆良,-,均荣,-,-,-,-,宣扬,筠霓&爱慈,NaN,NaN,领唱: 庆良代替洛圣
23,NaN,NaN,16,五,18 父亲节,小组聚会 14,均荣,-,歆妤,-,凯悦,-,-,-,-,均荣,依晶&艺汶,NaN,NaN,NaN
24,NaN,NaN,23,五,NaN,团契(Joshua) & 上半年生日会,约书亚组,-,美怡,宣扬,宣扬,-,-,-,歆妤,-,青年团,NaN,NaN,NaN
25,NaN,NaN,30,五,29 Haji,小组聚会 15,诗怡,-,依晶,-,键劲,-,-,-,-,艺汶,键劲&庆武,NaN,NaN,祷告: 艺汶代替洛圣
26,力飞,Jul,6,四,NaN,启发课程 1《生命就是如此吗？》,谢慧敏传道,键劲,美怡,-,宣扬,-,-,-,贤杰,-,青年团,欢迎歌、朋友、我的未来不是梦,宾果/创意介绍,NaN
27,NaN,NaN,8,六,NaN,青少年讲座《事奉者联盟 The Disciples》,张俊贤教师,-,宣扬,美怡,键劲,佳欣,凯悦,力飞,洛圣,-,青年团,-,-,NaN
28,NaN,NaN,9,日,NaN,青少主日《Be Light·光》,张俊贤教师,-,爱慈,宣扬,键劲,佳欣,凯悦,均荣,依晶,-,-,-,-,NaN
29,NaN,NaN,9,日,NaN,青少主日爱筵,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN
30,NaN,NaN,13,四,NaN,启发课程 2《耶稣是谁？》,谢慧敏传道,爱慈,健劲,-,均荣,-,-,-,贤杰,-,青年团,朋友、光辉岁月、耶稣对你真好/是耶稣,猜猜我是谁/真真假假,NaN
31,NaN,NaN,16,日,NaN,青少年义卖会,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN
32,NaN,NaN,20,四,19 Awal Muharram,启发课程 3《耶稣为什么死？》,谢慧敏传道,美怡,宣扬,-,-,佳欣,-,-,贤杰,-,青年团,主恩典、幸福、有一位神,音乐传球,NaN
33,NaN,NaN,23,日,NaN,羽毛球友谊赛,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN
34,NaN,NaN,27,四,NaN,启发课程 4《如何得着信心？》,谢慧敏传道,依晶,爱慈,-,宣扬,-,-,-,贤杰,-,青年团,不动摇的信心、恩典够用、我相信,剪刀石头布,NaN
35,NaN,NaN,30,日,NaN,羽毛球决赛,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN
36,洛圣,Aug,4,五,NaN,启发课程 5《为什么祷告？怎样祷告？》,谢慧敏传道,诗怡,美怡,-,健劲,-,-,-,贤杰,-,青年团,满有能力、我相信、倾听我的心,数学炸弹,破冰: 诗怡代替宣扬，宣扬: 8月1-4日不在拿笃
37,NaN,NaN,11,五,NaN,启发课程 6《为什么读圣经？怎样读圣经？》,谢慧敏传道,力飞,健劲,-,-,佳欣,-,-,贤杰,-,青年团,朋友、认定你、耶稣爱你,Emoji成语,NaN
38,NaN,NaN,18,五,NaN,启发课程 7《上帝如何指引我们？》,谢慧敏传道,洛圣,宣扬,-,凯悦,-,-,-,贤杰,-,青年团,脚步、恩典之路,请你跟我这样做,NaN
39,NaN,NaN,25,五,NaN,启发课程 8《如何抵挡邪恶》,谢慧敏传道,贤杰,爱慈,-,均荣,-,-,-,贤杰,-,青年团,大山为我挪开、耶稣掌权、有一天,萝卜蹲,NaN
40,NaN,NaN,31,四,NaN,启发课程 9《圣灵》*启发周末营,?,?,宣扬,力添,健劲,佳欣,凯悦,力飞,贤杰,-,?,圣灵的江河、求主充满我、圣灵请你来/圣灵请你来充满我心,猫抓老鼠,NaN
41,贤杰,Sep,8,五,NaN,启发课程 10《为什么要传福音？怎样传福音？》,谢慧敏传道,键劲,美怡,-,-,佳欣,-,-,贤杰,-,青年团,传爱、真正好、人们需要主,剪刀石头布与橡皮筋,NaN
42,NaN,NaN,15,五,16 Malaysia Day,启发课程 11《上帝今天还医治人吗？》,谢慧敏传道,爱慈,健劲,-,宣扬,-,-,-,贤杰,-,青年团,美好事、唯有耶稣、医治的爱,比一比,NaN
43,NaN,NaN,22,五,29中秋节,启发课程 12《教会是什么》&预祝中秋,谢慧敏传道,美怡,宣扬,-,均荣,-,-,-,贤杰,-,青年团,在主爱中、看见神的爱、我们爱让世界不一样,鸡蛋小鸡母鸡,NaN
44,NaN,NaN,30,六,28 先知诞辰,启发课程 13《如何活得更精彩》*启发之夜,?,?,爱慈,宣扬,键劲,佳欣,凯悦,均荣,依晶,-,?,恩典已降临、活出爱、我需要有你在我生命中,树与松鼠,NaN
45,键劲,Oct,6,五,7 州元首诞辰,小组聚会 16,键劲,-,淑怡,-,均荣,-,-,-,-,爱慈,力添&力炫,NaN,NaN,NaN
46,NaN,NaN,13,五,NaN,区青少联谊(或改去21日),青年团,-,爱慈,宣扬,键劲,佳欣,凯悦,均荣,依晶,-,青年团,NaN,NaN,NaN
47,NaN,NaN,20,五,NaN,小组聚会 17,美怡,-,歆妤,-,凯悦,-,-,-,-,健劲,健祺&仙平,NaN,NaN,NaN
48,NaN,NaN,27,五,NaN,团契(John),约翰组,-,宣扬,洛圣,宣扬,-,-,-,力飞,-,青年团,NaN,NaN,NaN
49,爱慈,Nov,3,五,NaN,布置教堂,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
50,NaN,NaN,10,五,12 屠妖节,布置教堂,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
51,NaN,NaN,17,五,NaN,布置教堂,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
52,NaN,NaN,24,五,NaN,布置教堂,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
53,美怡,Dec,1,五,NaN,布置教堂,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
54,NaN,NaN,8,五,NaN,布置教堂,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
55,NaN,NaN,15,五,NaN,练习报佳音诗歌,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
56,NaN,NaN,23,六,22 冬至,预祝圣诞 & 下半年生日会,青年团,-,宣扬,爱慈,键劲,佳欣,凯悦,均荣,贤杰,-,青年团,NaN,NaN,NaN
57,NaN,NaN,29,五,NaN,暂停,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN